name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/pyproject.toml') }}

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Create .env.test
        run: |
          cat > .env.test << EOF
          HF_TOKEN=${{ secrets.HF_TOKEN }}
          HF_USERNAME=${{ secrets.HF_USERNAME }}
          FLASK_ENV=testing
          EOF

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/ -v --cov=app --cov-report=xml --cov-report=term
